FROM node:22.0.0-alpine3.18 AS builder

WORKDIR /home/app/shared_core

COPY shared_core/package*.json      /home/app/shared_core/

RUN npm ci

COPY shared_core /home/app/shared_core
RUN npm run build

# Final image
FROM nginx:stable-alpine

COPY shared_core/nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /home/app/shared_core/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]