export type {
  MfeCallbacks,
  MfeDataSet,
  MfeScope,
  MfeMountOptions,
  MfeModule,
  SharedComponentModule,
} from "@shared-core/types/mfe";
export type { InheritedContext } from "@shared-core/types/contexts";
export type {
  DefaultProps,
  InheritedProviderProps,
  AnchorCircularProps,
  ButtonBlackProps,
  ButtonWhiteProps,
  ColorCircleProps,
  CounterWithActionsProps,
  FormSearchProps,
  ImageWithBackgroundColorProps,
  InformationItemClothesProps,
  LoaderCircularProps,
  MenuScreenWhiteProps,
  MfeErrorBoundaryProps,
  RateStarsProps,
  SkeletonShimmerProps,
  SliderSnapXProps,
  SvgArrowLeftProps,
  SvgArrowRightProps,
  SvgCartShoppingProps,
  SvgCheckProps,
  SvgChevronDownProps,
  SvgChevronUpProps,
  SvgCloseProps,
  SvgFacebookProps,
  SvgHamburgerMenuProps,
  SvgInstagramProps,
  SvgSearchProps,
  SvgSkyStarProps,
  SvgStarToFillProps,
  SvgTwitterProps,
  TagSimpleProps,
} from "@shared-core/types/props";
export type { Locale, Clothes, Color, Image, Product, Review, Size } from "@shared-core/types/app";
