name: dshop-dev
services:
  dshop-container:
    build:
      context: ./container
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./container/.env
    volumes:
      - ./container:/home/app:rw
      - ./shared_core-types:/home/shared_core-types:ro
      - ./shared_react-types:/home/shared_react-types:ro
      - ./shared_angular-types:/home/shared_angular-types:ro
      - ./product_detail-types:/home/product_detail-types:ro
      - ./home-types:/home/home-types:ro
      - dshop_container_node_modules:/home/app/node_modules
    ports:
      - 8080:8080
    depends_on:
      dshop-home:
        condition: service_started
    command: >
      sh -c "
        npm config set install-links true &&
        npm install &&
        npm run start
      "
    networks:
      - dshop-dev-net

  dshop-home:
    build:
      context: ./home
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./home/.env
    volumes:
      - ./home:/home/app:rw
      - ./shared_core-types:/home/shared_core-types:ro
      - ./shared_react-types:/home/shared_react-types:ro
      - ./shared_angular-types:/home/shared_angular-types:ro
      - dshop_home_node_modules:/home/app/node_modules
    ports:
      - 8081:8081
    depends_on:
      dshop-shared-react:
        condition: service_started
      dshop-shared-angular:
        condition: service_started
    command: >
      sh -c "
        npm config set install-links true &&
        npm install &&
        npm run start
      "
    networks:
      - dshop-dev-net

  dshop-product-detail:
    build:
      context: ./product_detail
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./product_detail/.env
    volumes:
      - ./product_detail:/home/app:rw
      - ./shared_core-types:/home/shared_core-types:ro
      - dshop_product_detail_node_modules:/home/app/node_modules
    ports:
      - 8085:8085
    depends_on:
      dshop-shared-react:
        condition: service_started
      dshop-shared-angular:
        condition: service_started
    command: >
      sh -c "
        npm config set install-links true &&
        npm install &&
        npm run start
      "
    networks:
      - dshop-dev-net

  dshop-shared-react:
    build:
      context: ./shared_react
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./shared_react/.env
    volumes:
      - ./shared_react:/home/app:rw
      - ./shared_core-types:/home/shared_core-types:ro
      - dshop_shared_react_node_modules:/home/app/node_modules
    ports:
      - 8082:8082
    depends_on:
      dshop-shared-core:
        condition: service_started
    command: >
      sh -c "
        npm config set install-links true &&
        npm install &&
        npm run start
      "
    networks:
      - dshop-dev-net

  dshop-shared-angular:
    build:
      context: ./shared_angular
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./shared_angular/.env
    volumes:
      - ./shared_angular:/home/app:rw
      - ./shared_core-types:/home/shared_core-types:ro
      - dshop_shared_angular_node_modules:/home/app/node_modules
    ports:
      - 8083:8083
    depends_on:
      dshop-shared-core:
        condition: service_started
    command: >
      sh -c "
        npm config set install-links true &&
        npm install &&
        npm run start
      "
    networks:
      - dshop-dev-net

  dshop-shared-core:
    build:
      context: ./shared_core
      dockerfile: Dockerfile.development
    restart: always
    env_file:
      - ./shared_core/.env
    volumes:
      - ./shared_core:/home/app:rw
      - dshop_shared_core_node_modules:/home/app/node_modules
    ports:
      - 8084:8084
    command: >
      sh -c "
        npm install &&
        npm run start
      "
    networks:
      - dshop-dev-net

networks:
  dshop-dev-net:

volumes:
  dshop_shared_core_node_modules:
  dshop_shared_react_node_modules:
  dshop_shared_angular_node_modules:
  dshop_product_detail_node_modules:
  dshop_home_node_modules:
  dshop_container_node_modules:
