name: dshop-dev
services:
  dshop-container:
    build:
      context: ./container
      dockerfile: Dockerfile.development
    restart: unless-stopped
    env_file:
      - ./container/.env
    volumes:
      - ./container:/home/app
      - ./shared-core:/home/shared-core
      - ./shared-react:/home/shared-react
      - ./shared-angular:/home/shared-angular
      - /home/app/node_modules
    ports:
      - 3000:3000
    networks:
      - dshop-dev-net
    depends_on:
      - dshop-home
      - dshop-product-detail
    stdin_open: true
    tty: true

  dshop-home:
    build:
      context: ./home
      dockerfile: Dockerfile.development
    restart: unless-stopped
    env_file:
      - ./home/.env
    volumes:
      - ./home:/home/app
      - ./shared-core:/home/shared-core
      - ./shared-react:/home/shared-react
      - ./shared-angular:/home/shared-angular
      - /home/app/node_modules
    ports:
      - 3010:3010
    networks:
      - dshop-dev-net
    depends_on:
      - dshop-shared-react
      - dshop-shared-angular
    stdin_open: true
    tty: true

  dshop-product-detail:
    build:
      context: ./product-detail
      dockerfile: Dockerfile.development
    restart: unless-stopped
    env_file:
      - ./product-detail/.env
    volumes:
      - ./product-detail:/home/app
      - ./shared-core:/home/shared-core
      - ./shared-react:/home/shared-react
      - ./shared-angular:/home/shared-angular
      - /home/app/node_modules
    ports:
      - 3020:3020
    networks:
      - dshop-dev-net
    depends_on:
      - dshop-shared-react
      - dshop-shared-angular
    stdin_open: true
    tty: true

  dshop-shared-react:
    build:
      context: ./shared-react
      dockerfile: Dockerfile.development
    restart: unless-stopped
    env_file:
      - ./shared-react/.env
    volumes:
      - ./shared-react:/home/app
      - ./shared-core:/home/shared-core
      - /home/app/node_modules
    ports:
      - 4010:4010
    networks:
      - dshop-dev-net
    depends_on:
      - dshop-shared-core
    stdin_open: true
    tty: true

  dshop-shared-angular:
    build:
      context: ./shared-angular
      dockerfile: Dockerfile.development
    restart: unless-stopped
    env_file:
      - ./shared-angular/.env
    volumes:
      - ./shared-angular:/home/app
      - ./shared-core:/home/shared-core
      - /home/app/node_modules
    ports:
      - 4020:4020
    networks:
      - dshop-dev-net
    depends_on:
      - dshop-shared-core
    stdin_open: true
    tty: true

  dshop-shared-core:
    build:
      context: ./shared-core
      dockerfile: Dockerfile.development
    restart: unless-stopped
    env_file:
      - ./shared-core/.env
    volumes:
      - ./shared-core:/home/app
      - /home/app/node_modules
    ports:
      - 4000:4000
    networks:
      - dshop-dev-net
    stdin_open: true
    tty: true

networks:
  dshop-dev-net:
