name: dshop-prod
services:
  dshop-container:
    build:
      context: .
      dockerfile: ./container/Dockerfile.production
    restart: always
    env_file:
      - ./container/.env
    ports:
      - 8080:80
    depends_on:
      dshop-home:
        condition: service_started
    networks:
      - dshop-prod-net

  dshop-home:
    build:
      context: .
      dockerfile: ./home/Dockerfile.production
    restart: always
    env_file:
      - ./home/.env
    ports:
      - 8081:80
    depends_on:
      dshop-shared-react:
        condition: service_started
      dshop-shared-angular:
        condition: service_started
    networks:
      - dshop-prod-net

  dshop-product-detail:
    build:
      context: .
      dockerfile: ./product_detail/Dockerfile.production
    restart: always
    env_file:
      - ./product_detail/.env
    ports:
      - 8085:80
    depends_on:
      dshop-shared-react:
        condition: service_started
      dshop-shared-angular:
        condition: service_started
    networks:
      - dshop-prod-net

  dshop-shared-react:
    build:
      context: .
      dockerfile: ./shared_react/Dockerfile.production
    restart: always
    env_file:
      - ./shared_react/.env
    ports:
      - 8082:80
    depends_on:
      dshop-shared-core:
        condition: service_started
    networks:
      - dshop-prod-net

  dshop-shared-angular:
    build:
      context: .
      dockerfile: ./shared_angular/Dockerfile.production
    restart: always
    env_file:
      - ./shared_angular/.env
    ports:
      - 8083:80
    depends_on:
      dshop-shared-core:
        condition: service_started
    networks:
      - dshop-prod-net

  dshop-shared-core:
    build:
      context: .
      dockerfile: ./shared_core/Dockerfile.production
    restart: always
    env_file:
      - ./shared_core/.env
    ports:
      - 8084:80
    networks:
      - dshop-prod-net

networks:
  dshop-prod-net:
