name: dshop-prod

services:
  container:
    image: ghcr.io/diegolibonati/dshop-container:latest
    restart: always
    ports:
      - "${APP_PORT:-8180}:8080"
    networks:
      - dshop-prod-net
    depends_on:
      - shared-core
      - shared-react
      - shared-angular
      - home
      - product-detail
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  home:
    image: ghcr.io/diegolibonati/dshop-home:latest
    restart: always
    networks:
      - dshop-prod-net
    depends_on:
      - shared-core
      - shared-react
      - shared-angular

  product-detail:
    image: ghcr.io/diegolibonati/dshop-product-detail:latest
    restart: always
    networks:
      - dshop-prod-net
    depends_on:
      - shared-core
      - shared-react
      - shared-angular

  shared-react:
    image: ghcr.io/diegolibonati/dshop-shared-react:latest
    restart: always
    networks:
      - dshop-prod-net
    depends_on:
      - shared-core

  shared-angular:
    image: ghcr.io/diegolibonati/dshop-shared-angular:latest
    restart: always
    networks:
      - dshop-prod-net
    depends_on:
      - shared-core

  shared-core:
    image: ghcr.io/diegolibonati/dshop-shared-core:latest
    restart: always
    networks:
      - dshop-prod-net

networks:
  dshop-prod-net:
