name: dshop-prod

services:
  container:
    build:
      context: .
      dockerfile: container/Dockerfile.production
      args:
        VITE_REMOTE_SHARED_CORE_URL: ${VITE_REMOTE_SHARED_CORE_URL:-/mfe/shared-core/remoteEntry.js}
        VITE_REMOTE_SHARED_REACT_URL: ${VITE_REMOTE_SHARED_REACT_URL:-/mfe/shared-react/remoteEntry.js}
        VITE_REMOTE_SHARED_ANGULAR_URL: ${VITE_REMOTE_SHARED_ANGULAR_URL:-/mfe/shared-angular/remoteEntry.js}
        VITE_REMOTE_HOME_URL: ${VITE_REMOTE_HOME_URL:-/mfe/home/remoteEntry.js}
        VITE_REMOTE_PRODUCT_DETAIL_URL: ${VITE_REMOTE_PRODUCT_DETAIL_URL:-/mfe/product-detail/remoteEntry.js}
    restart: always
    ports:
      - 8080:8080
    networks:
      - dshop-prod-net
    depends_on:
      - shared-core
      - shared-react
      - shared-angular
      - home
      - product-detail

  home:
    build:
      context: .
      dockerfile: home/Dockerfile.production
      args:
        VITE_REMOTE_SHARED_CORE_URL: ${VITE_REMOTE_SHARED_CORE_URL:-/mfe/shared-core/remoteEntry.js}
        VITE_REMOTE_SHARED_REACT_URL: ${VITE_REMOTE_SHARED_REACT_URL:-/mfe/shared-react/remoteEntry.js}
        VITE_REMOTE_SHARED_ANGULAR_URL: ${VITE_REMOTE_SHARED_ANGULAR_URL:-/mfe/shared-angular/remoteEntry.js}
    restart: always
    networks:
      - dshop-prod-net
    depends_on:
      - shared-core
      - shared-react
      - shared-angular

  product-detail:
    build:
      context: .
      dockerfile: product-detail/Dockerfile.production
      args:
        VITE_REMOTE_SHARED_CORE_URL: ${VITE_REMOTE_SHARED_CORE_URL:-/mfe/shared-core/remoteEntry.js}
        VITE_REMOTE_SHARED_REACT_URL: ${VITE_REMOTE_SHARED_REACT_URL:-/mfe/shared-react/remoteEntry.js}
        VITE_REMOTE_SHARED_ANGULAR_URL: ${VITE_REMOTE_SHARED_ANGULAR_URL:-/mfe/shared-angular/remoteEntry.js}
    restart: always
    networks:
      - dshop-prod-net
    depends_on:
      - shared-core
      - shared-react
      - shared-angular

  shared-react:
    build:
      context: .
      dockerfile: shared-react/Dockerfile.production
      args:
        VITE_REMOTE_SHARED_CORE_URL: ${VITE_REMOTE_SHARED_CORE_URL:-/mfe/shared-core/remoteEntry.js}
    restart: always
    networks:
      - dshop-prod-net
    depends_on:
      - shared-core

  shared-angular:
    build:
      context: .
      dockerfile: shared-angular/Dockerfile.production
      args:
        VITE_REMOTE_SHARED_CORE_URL: ${VITE_REMOTE_SHARED_CORE_URL:-/mfe/shared-core/remoteEntry.js}
    restart: always
    networks:
      - dshop-prod-net
    depends_on:
      - shared-core

  shared-core:
    build:
      context: .
      dockerfile: shared-core/Dockerfile.production
    restart: always
    networks:
      - dshop-prod-net

networks:
  dshop-prod-net:
