import type { Clothes } from "shared-core/sdk";

export const CLOTHES_1: Clothes[] = [
  {
    id: "cl-001",
    src: "https://www.pngall.com/wp-content/uploads/14/White-T-Shirt-PNG-Photo.png",
    name: "Casual White T-Shirt",
    rate: 4.5,
    price: 19.99,
    discount: 0,
  },
  {
    id: "cl-002",
    src: "https://png.pngtree.com/png-vector/20240613/ourmid/pngtree-blue-jean-jacket-free-png-image_12715682.png",
    name: "Blue Denim Jacket",
    rate: 4.7,
    price: 59.99,
    discount: 15,
  },
  {
    id: "cl-003",
    src: "https://png.pngtree.com/png-vector/20240411/ourmid/pngtree-women-s-black-leather-jacket-transparent-background-generative-ai-png-image_12280771.png",
    name: "Black Leather Jacket",
    rate: 4.8,
    price: 149.99,
    discount: 20,
  },
  {
    id: "cl-004",
    src: "https://png.pngtree.com/png-vector/20240202/ourmid/pngtree-isolated-grey-hoodie-front-png-image_11590694.png",
    name: "Gray Hoodie",
    rate: 4.3,
    price: 39.99,
    discount: 10,
  },
  {
    id: "cl-005",
    src: "https://static.vecteezy.com/system/resources/previews/058/171/358/non_2x/classic-blue-jeans-isolated-on-a-transparent-background-for-clothing-display-and-fashion-inspiration-blue-jeans-isolated-on-transparent-free-png.png",
    name: "Classic Blue Jeans",
    rate: 4.6,
    price: 49.99,
    discount: 5,
  },
  {
    id: "cl-006",
    src: "https://pngimg.com/d/dress_shirt_PNG8070.png",
    name: "Formal White Shirt",
    rate: 4.4,
    price: 34.99,
    discount: 0,
  },
  {
    id: "cl-007",
    src: "https://static.vecteezy.com/system/resources/thumbnails/060/353/836/small_2x/elegant-red-floral-dress-summer-fashion-apparel-stylish-feminine-garment-cut-out-transparent-png.png",
    name: "Red Summer Dress",
    rate: 4.7,
    price: 69.99,
    discount: 12,
  },
  {
    id: "cl-008",
    src: "https://andsons.co.uk/cdn/shop/products/Chino_20Virgil_20Army_20Green_20FLATLAY_201.png?v=1641914358&width=640",
    name: "Green Chinos",
    rate: 4.2,
    price: 44.99,
    discount: 8,
  },
  {
    id: "cl-010",
    src: "https://static.vecteezy.com/system/resources/previews/055/240/026/non_2x/winter-coat-on-white-background-on-transparent-background-png.png",
    name: "Wool Winter Coat",
    rate: 4.8,
    price: 199.99,
    discount: 25,
  },
];
