FROM node:21.1.0-alpine3.18 AS builder

WORKDIR /home/app

COPY . .

RUN npm install && npm run build

# Final image
FROM nginx:stable-alpine

COPY --from=builder /home/app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]